apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
data:
# NOTA: NO USAR NUNCA PASSWORDS EN TEXTO PLANO. ESTE SECRET ES SOLO COMO EJEMPLO DIDÁCTICO.
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL2RidXNlcjpkYnBhc3N3b3JkQG1hcmlhZGI6MzMwNi9jb3Vyc2VzX2Ri
