apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
# NOTA: NO USAR NUNCA PASSWORDS EN TEXTO PLANO. ESTE SECRET ES SOLO COMO EJEMPLO DIDÁCTICO.
  MARIADB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk        # 'rootpassword' en base64
  MARIADB_USER: ZGJ1c2Vy                         # 'dbuser' en base64
  MARIADB_PASSWORD: ZGJwYXNzd29yZA==             # 'dbpassword' en base64
